from logging import exception



try:
    print(index)
except exception as e:
    print(e)